# GitHub Actions CI/CD Pipeline

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Tejas@12345
          MYSQL_DATABASE: shoppers_db
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p12345"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: Tejas%40123
          POSTGRES_DB: shoppers_warehouse
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for databases
        run: |
          sleep 20

      - name: Create model directory
        run: |
          mkdir -p ml
      - name: Wait for databases
        run: |
          sleep 20

      
      - name: Setup database and train model
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: Tejas@12345
          DB_NAME: shoppers_db

          PG_HOST: 127.0.0.1
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: Tejas@123
          PG_NAME: shoppers_warehouse

          MLFLOW_TRACKING_URI: ./mlruns
          MODEL_PATH: ./ml/model.pkl

        run: |
          python data/reload_data.py
          python etl/load.py
          python ml/train.py

      - name: Run pytest
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: Tejas@12345
          DB_NAME: shopper_db1

          PG_HOST: 127.0.0.1
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: Tejas@123
          PG_NAME: shoppers_warehouse

          MLFLOW_TRACKING_URI: ./mlruns
          MODEL_PATH: ./ml/model.pkl

        run: |
          pytest tests/test_api.py -v

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shoppers-ml:latest